### ISSUE TITLE
Joke Time

### ISSUE THREAD

**Issue by Iulian33** [steevehook/CobotFinalRelease#1]
Cand apare Joke ar fi bine sa ashtepte nu 10 secunde ci 5 fiindca userul ashtepata mi se pare prea mult neavind nici o optiune si ramine confuz  nu shtie ce sa faca si este tentat ca sa dea refresh  penteu a incepe o converstie  cu toate ca dupa 10 secunde apare acea gluma si are si optiunea de a incepe din nou conversatia

**Comment by steevehook** [comment]
Done it
